return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "rose-pine-main",
    },
  },
  { "ellisonleao/gruvbox.nvim" },
  { "rose-pine/neovim", name = "rose-pine" },
  -- Configure LazyVim to load gruvbox
  {
    "folke/tokyonight.nvim",
    opts = {
      transparent = true,
      styles = {
        sidebars = "transparent",
        floats = "transparent",
      },
    },
  },
  { "rktjmp/lush.nvim" },
  -- { "nyoom-engineering/oxocarbon.nvim", opts = { background = "dark" } },
  { "maxmx03/FluoroMachine.nvim" },
  { "shaunsingh/moonlight.nvim" },
  { "olivercederborg/poimandres.nvim" },
  { "JoosepAlviste/palenightfall.nvim" },
  { "xero/miasma.nvim" },
  { "yonlu/omni.vim" },
  { "shrikecode/kyotonight.vim" },
  { "numToStr/Sakura.nvim" },
  { "luisiacc/the-matrix.nvim" },
  { "Scysta/pink-panic.nvim" },
  {
    "catppuccin/nvim",
    opts = {
      integrations = {
        aerial = true,
        alpha = true,
        cmp = true,
        dashboard = true,
        flash = true,
        grug_far = true,
        gitsigns = true,
        headlines = true,
        illuminate = true,
        indent_blankline = { enabled = true },
        leap = true,
        lsp_trouble = true,
        mason = true,
        markdown = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        navic = { enabled = true, custom_bg = "lualine" },
        neotest = true,
        neotree = true,
        noice = true,
        notify = true,
        semantic_tokens = true,
        telescope = true,
        treesitter = true,
        treesitter_context = true,
        which_key = true,
      },
    },
  },
}
